[colors.primary]
background = "#1b1b22"
foreground = "#9ca1b6"

[colors.normal]
black = "#22212c"
red = "#906775"
green = "#6a8578"
yellow = "#a68686"
blue = "#848cb2"
magenta = "#927794"
cyan = "#86a3a6"
white = "#aebae9"

[colors.bright]
black = "#302f3f"
red = "#ae8093"
green = "#86a28f"
yellow = "#c19b9b"
blue = "#9da4c8"
magenta = "#ad8eab"
cyan = "#9bb9c1"
white = "#d9d6e9"
