[colors.primary]
background = "#202023"
foreground = "#d9d6e9"

[colors.normal]
black = "#202023"
red = "#9c6b7a"
green = "#838984"
yellow = "#c4afa2"
blue = "#8d96bd"
magenta = "#b694b6"
cyan = "#86a3a6"
white = "#33333b"

[colors.bright]
black = "#29292c"
red = "#ae808f"
green = "#8d9b92"
yellow = "#e0cca8"
blue = "#9da4c8"
magenta = "#d2aece"
cyan = "#9cb9c0"
white = "#d9d6e9"
