# Author: Monocled

"keyword" = "white"
"constant" = "white"

"function.macro" = "cyan"
"tag" = "cyan"
"function" = "cyan"

"comment" = { fg = "bright_cyan", modifiers = ["italic"] }

"namespace" = "blue"
"type" = "blue"

"operator" = "yellow"
"special" = "yellow"
"constructor" = "yellow"
"label" = "yellow"
"attribute" = "bright_yellow"

"variable" = "magenta"

"string" = "white"

"ui.background" = { bg = "black" }
"ui.background.separator" = { fg = "white "}

"ui.selection" = { bg = "bright_black", fg = "bright_yellow" }

"ui.statusline" = { fg = "white", bg = "bright_black" }
"ui.statusline.select" = { fg = "cyan" }
"ui.statusline.insert" = { fg = "yellow" }

"ui.linenr" = { fg = "white", bg = "bright_black" }
"ui.linenr.selected" = { fg = "bright_yellow", bg = "brighter_black" }
"ui.gutter" = { bg = "bright_black" }
"ui.gutter.selected" = { fg = "bright_yellow", bg = "brighter_black" } 

"ui.menu" = { fg = "white", bg = "bright_black" }
"ui.menu.selected" = { fg = "bright_yellow", bg = "brighter_black" }
"ui.menu.scroll" = { fg = "bright_white", bg = "bright_black"}

"ui.cursor" = { bg = "white", fg = "bright_black" }
"ui.cursor.match" = { bg = "bright_cyan"  }

warning = "bright_yellow"
error = "bright_red"
info = "bright_cyan"
hint = "bright_cyan"

[palette]
black = "#202023"
bright_black = "#29292c"
brighter_black = "#33333b"

red = "#838984"
bright_red = "#ae808f"

green = "#838984"
bright_green = "#8d9b92"

yellow = "#c4afa2"
bright_yellow = "#e0cca8"

blue = "#8d96bd"
bright_blue = "#9da4c8"

magenta = "#b694b6"
bright_magenta = "#d2aece"

cyan = "#86a3a6"
bright_cyan = "#9cb9c0"

white = "#d9d6e9"
