[colors]
background = "#202023"
foreground = "#d9d6e9"

cursor = "#d9d6e9"
vi-cursor = "#d9d6e9"

selection-background = "#d9d6e9"
selection-foreground = "#202023"

tabs = '#86a3a6'
tabs-foreground = '#d9d6e9'
tabs-active = '#33333b'
tabs-active-highlight = '#e0cca8'
tabs-active-foreground = '#d9d6e9'
bar = '#29292c'

search-match-background = '#202023'
search-match-foreground = '#d9d6e9'
search-focused-match-background = '#202023'
search-focused-match-foreground = '#d9d6e9'

black = "#202023"
red = "#9c6b7a"
green = "#838984"
yellow = "#c4afa2"
blue = "#8d96bd"
magenta = "#b694b6"
cyan = "#86a3a6"
white = "#33333b"

light-black = "#29292c"
light-red = "#ae808f"
light-green = "#8d9b92"
light-yellow = "#e0cca8"
light-blue = "#9da4c8"
light-magenta = "#d2aece"
light-cyan = "#9cb9c0"
light-white = "#d9d6e9"
