[metadata]
name = "petrichor-overcast"
author = "Sebaguardian"
origin_url = "https://github.com/PersonForSure/petrichor"

[colors]
foreground = "#d9d6e9"
background = "#202023"
cursor_bg = "#d9d6e9"
cursor_border = "#c3c6d3"
cursor_fg = "#d9d6e9"
compose_cursor = "#d9d6e9"
selection_bg = "#d9d6e9"
selection_fg = "#202023"
scrollbar_thumb = "#8d96bd"
split = "#29292c"
visual_bell = "#d9d6e9"
ansi = ["#202023", "#9c6b7a", "#838984", "#c4afa2", "#8d96bd", "#b694b6", "#86a3a6", "#33333b"]
brights = ["#29292c", "#ae808f", "#8d9b92", "#e0cca8", "#9da4c8", "#d2aece", "#9cb9c0", "#d9d6e9"]

[colors.tab_bar]
background = "#202023"
inactive_tab_edge = "#202023"
inactive_tab_edge_hover = "#33333b"

[colors.tab_bar.active_tab]
bg_color = "#86a3a6"
fg_color = "#d9d6e9"
intensity = "Normal"
italic = false
strikethrough = false
underline = "None"

[colors.tab_bar.inactive_tab]
bg_color = "#202023"
fg_color = "#d9d6e9"
intensity = "Normal"
italic = false
strikethrough = false
underline = "None"

[colors.tab_bar.inactive_tab_hover]
bg_color = "#33333b"
fg_color = "#d9d6e9"
intensity = "Normal"
italic = false
strikethrough = false
underline = "None"

[colors.tab_bar.new_tab]
bg_color = "#202023"
fg_color = "#d9d6e9"
intensity = "Normal"
italic = false
strikethrough = false
underline = "None"

[colors.tab_bar.new_tab_hover]
bg_color = "#33333b"
fg_color = "#d9d6e9"
intensity = "Normal"
italic = false
strikethrough = false
underline = "None"
