[metadata]
name = "petrichor-dew"
author = "Sebaguardian"
origin_url = "https://github.com/PersonForSure/petrichor"

[colors]
foreground = "#9ca1b6"
background = "#1c1c20"
cursor_bg = "#9ca1b6"
cursor_border = "#9ca1b6"
cursor_fg = "#1c1c20"
compose_cursor = "#9ca1b6"
selection_bg = "#9ca1b6"
selection_fg = "#1c1c20"
scrollbar_thumb = "#858db3"
split = "#27252c"
visual_bell = "#9ca1b6"
ansi = ["#27252c", "#906775", "#947f6b", "#ab8575", "#858db3", "#927aa3", "#86a6a6", "#aebae9"]
brights = ["#33313d", "#ae8093", "#7e9984", "#cba38c", "#a5abd8", "#b19cc2", "#9bc1c1", "#dfd6e9"]

[colors.tab_bar]
background = "#1c1c20"
inactive_tab_edge = "#1c1c20"
inactive_tab_edge_hover = "#33313d"

[colors.tab_bar.active_tab]
bg_color = "#86a6a6"
fg_color = "#9ca1b6"
intensity = "Normal"
italic = false
strikethrough = false
underline = "None"

[colors.tab_bar.inactive_tab]
bg_color = "#1c1c20"
fg_color = "#9ca1b6"
intensity = "Normal"
italic = false
strikethrough = false
underline = "None"

[colors.tab_bar.inactive_tab_hover]
bg_color = "#33313d"
fg_color = "#9ca1b6"
intensity = "Normal"
italic = false
strikethrough = false
underline = "None"

[colors.tab_bar.new_tab]
bg_color = "#1c1c20"
fg_color = "#9ca1b6"
intensity = "Normal"
italic = false
strikethrough = false
underline = "None"

[colors.tab_bar.new_tab_hover]
bg_color = "#33313d"
fg_color = "#9ca1b6"
intensity = "Normal"
italic = false
strikethrough = false
underline = "None"
