[metadata]
name = "petrichor-downpour"
author = "Sebaguardian"
origin_url = "https://github.com/PersonForSure/petrichor"

[colors]
foreground = "#9ca1b6"
background = "#1b1b22"
cursor_bg = "#9ca1b6"
cursor_border = "#9ca1b6"
cursor_fg = "#1b1b22"
compose_cursor = "#9ca1b6"
selection_bg = "#9ca1b6"
selection_fg = "#1b1b22"
scrollbar_thumb = "#848cb2"
split = "#22212c"
visual_bell = "#9ca1b6"
ansi = ["#22212c", "#906775", "#6a8578", "#a68686", "#848cb2", "#927794", "#86a3a6", "#aebae9"]
brights = ["#302f3f", "#ae8093", "#86a28f", "#c19b9b", "#9da4c8", "#ad8eab", "#9bb9c1", "#d9d6e9"]

[colors.tab_bar]
background = "#1b1b22"
inactive_tab_edge = "#1b1b22"
inactive_tab_edge_hover = "#302f3f"

[colors.tab_bar.active_tab]
bg_color = "#86a3a6"
fg_color = "#9ca1b6"
intensity = "Normal"
italic = false
strikethrough = false
underline = "None"

[colors.tab_bar.inactive_tab]
bg_color = "#1b1b22"
fg_color = "#9ca1b6"
intensity = "Normal"
italic = false
strikethrough = false
underline = "None"

[colors.tab_bar.inactive_tab_hover]
bg_color = "#302f3f"
fg_color = "#9ca1b6"
intensity = "Normal"
italic = false
strikethrough = false
underline = "None"

[colors.tab_bar.new_tab]
bg_color = "#1b1b22"
fg_color = "#9ca1b6"
intensity = "Normal"
italic = false
strikethrough = false
underline = "None"

[colors.tab_bar.new_tab_hover]
bg_color = "#302f3f"
fg_color = "#9ca1b6"
intensity = "Normal"
italic = false
strikethrough = false
underline = "None"
